cilium/certgen

cmd/certgen.go, internal/defaults/defaults.go, internal/generate/generate.go, internal/option/config.go
Add support for creating certificates for external workloads. This is
mostly similar to how hubble certs are generated, but in anticipation
of the need to create new client certs on demand the CA key is also
stored in the configmap.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> certgen: Add support for creating certs for external workloads

cmd/certgen.go, internal/defaults/defaults.go
Now that we support key generation for multiple purposes it is better
to not assume anything about what is wanted. Current use seems to
explicitly use the affected "generate" flags anyway, so this should
not have any impact on how Cilium is using this, apart from not
generating external workload certs by default as now.
After this change, if nothing specific is requested, nothing is done:
$ ./cilium-certgen --k8s-kubeconfig-path ~/.kube/config
INFO[0000] cilium-certgen 0.1.1                          subsys=cilium-certgen
INFO[0000] Successfully generated all 0 requested certificates.  subsys=cilium-certgen
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> defaults: Do not generate anything by default.

cmd/certgen.go, internal/defaults/defaults.go, internal/option/config.go
Keys generated for extarnal workloads can also be used for clustermesh
when deployed through clustermesh-apiserver. Rename to make it clear
that these are clustermesh-apiserver certs.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> certgen: Rename external workloads to clustermesh-apiserver

cmd/certgen.go, internal/defaults/defaults.go, internal/option/config.go
Add generation of clustermesh remote cluster cert.
Also change to not copy CA cert in other clustermesh-apiserver certs, generate all requested certs before storing any, and add individual flags for clustermesh-apiserver certs.
=> Add support for clustermesh remote cluster cert

cmd/certgen.go, internal/defaults/defaults.go, internal/option/config.go
This change makes `--cilium-namespace` the default namespace of all
secrets and configmaps.
One can still overwrite the namespace value of the Hubble specific
secrets or configmaps by explicitly setting `--hubble-*-namespace`. This
means that an explicitly set `--hubble-*-namespace` always takes
precendece over `--cilium-namespace`.
Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>
=> cmd: Use --cilium-namespace as the default for Hubble certs

cmd/certgen.go, internal/defaults/defaults.go, internal/generate/generate.go, internal/option/config.go
This change revamps the way CA secrets are used for both the Hubble and
the clustermesh-apiserver certificate authority. Now, in order for the
CA secret to be loaded from K8s (instead of generated from scratch), one
needs to provide the `--$CA-reuse-secret` flag.
The overall motivation for this change is twofold. First, it fixes a bug
where certgen would always try to load the clustermesh-apiserver-ca
secret (even if no clustermesh-apiserver certificates were requested).
Second, it tries to unify the behavior between the Hubble CA and the
clustermesh-apiserver CA.
If `--$CA-reuse-secret` is combined with the `--$CA-generate` flag, then
certgen tries to reuse an existing K8s secret before generating a new
CA. This is matches the previous behavior for the clustermesh-apiserver
CA.
If only …
=> Introduce flag to control CA secret reuse

internal/generate/generate.go
Before this patch, it was not possible to understand by looking at the certgen logs whether a Create or Update operation was performed.
=> log when Secret and ConfigMap are updated

cmd/certgen.go, internal/generate/generate.go
In an effort to minimize friction and integration with [cert-manager](https://cert-manager.io/), we're aiming to generate the TLS Secrets with the same `data` keys as it does.
The only missing `data` key is `ca.crt` which is the Certificate of the Authority that signed the TLS certificate in `tls.crt`. This PR populate the `ca.crt` key in `data` accordingly.
=> generate: add ca.crt to tls secrets

.github/workflows/build.yaml
Before this patch, git diff was used to ensure a clean state with respect to the git repository. While it could catch a modified or removed file, it would not fail when a file was not checked in git (i.e. untracked).
This patch uses git status instead of git diff, effectively catching untracked files as well.
=> ci: use git status instead of git diff to check for a clean state

cmd/certgen.go, internal/defaults/defaults.go, internal/option/config.go
Includes `*.mesh.cilium.io` by default in the list of SANs for the clustermesh-apiserver server certificate. The value is made configurable in case users want to override it or restrict to a specific subset.
=> certgen: include '*.mesh.cilium.io' in server cert

.github/workflows/build-images-release.yaml
This removes the `-ci` image tag and slackbot notifications from the
image release workflow, which are not used in this repository.
Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>
=> github: Remove workflow pieces not used by certgen

.github/workflows/build.yaml, Dockerfile
Update Go to 1.17.1 and drop the explicit `go vet` invocation. The `go test` command will automatically run `go vet` on all packages  being tested as of Go 1.10, see https://golang.org/doc/go1.10#test
=> Update Go and drop explicit `go vet` check

cmd/certgen.go, internal/defaults/defaults.go, internal/generate/generate.go, internal/option/config.go
Fixes: [#300](https://github.com/cilium/cilium-cli/issues/300)
This PR brings the certgen tool in line with how `cilium-cli` [generates](https://github.com/cilium/cilium-cli/blob/master/defaults/defaults.go#L16) CA [certificates](https://github.com/cilium/cilium-cli/blob/master/internal/certs/certs.go#L92-L96). These two tools being out of sync with how they generate causes issues like those found in  [#300](https://github.com/cilium/cilium-cli/issues/300). Since `cilium-cli` appears to be the standard Cilium is using moving froward, based on the documentation, this PR proposes a simple solution to ensure the `cilium-cli` will work as expected when Cilium is installed via Helm.
I elected not to change the names of the variables defined in `defaults.go` so as to avoid changing the actual …
=> Generate: Bring certgen inline with cilium-cli

.gitignore, cmd/certgen.go, internal/generate/generate.go
There might be a race condition if multiple certgen processes are running
at the same time with ca-reuse-secret and ca-generate flags enabled. The
sequence of flows could be as below:
P1 -> Confirm secret is not available
P2 -> Confirm secret is not available
P1 -> Generate new CA
P2 -> Generate new CA
P1 -> Store its generate CA to secret
P2 -> Store its generate CA to secret, which overwrite what P1 stored.
This commit is to make sure that we will throw IsAlreadyExists error if
the secret is available in StoreAsSecret function, then the caller (e.g
certgen) will decide if it should fail or just reload secret and proceed.
In above example, P2 will reload CA from secret accordingly.
Signed-off-by: Tam Mach <tam.mach@isovalent.com>
This is coming out of sync between myself, Sebastian and …
=> bug: Avoid race condition while generate secret with re-use flag

CODEOWNERS
Some teams were recently renamed, update the CODEOWNERS to reflect that.
=> CODEOWNERS: Fix renamed teams

.github/workflows/build.yaml
While here, also bump golangci-lint to v1.52.2.
Fixes: a0e66e12d1bdffa923568e057c0d676deb41aacc
=> ci: fix indentation of golangci-lint action

.github/workflows/build-images-release.yaml
Update `.github/workflows/build-images-release.yaml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml'  | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: |
echo ::set-output name=tag::${GITHUB_REF##*/}
```
**TO-BE**
```yml
run: |
echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
```
=> github: Replace deprecated command with environment file

.github/dependabot.yml
Given that this set of dependencies need to be updated at once, they were ignored by dependabot's config. However, with dependabot now having support for grouped updates, we can leverage the feature to let the bot update them all at once.
=> ci: let dependabot update k8s deps as a group of deps

Dockerfile, go.mod
Bump the build base golang image to alpine 3.19 on the way.
=> ci: Bump Go to v1.21.5

cmd/certgen.go
The admin certificate is used by the clustermesh-apiserver for client authentication against the sidecar etcd instance. Etcd leverages the common name to determine the user name, while SANs are ignored. Hence, let's just remove it, as not necessary. Additionally, let's do the same for all the other clustermesh client-auth certs, as by default the CN
is copied into the SAN section as well. This is consistent with the behavior of the other Cilium's autogeneration methods.
Related: cilium/cilium#32662
=> clustermesh: drop unnecessary localhost SAN from the admin certificate

.github/dependabot.yml, .github/workflows/build.yaml, RELEASE.md
For context, https://github.com/cilium/certgen/pull/220 will introduce a configuration breaking change and after discussion we will maintain patch release v0.1 branch for Cilium < v1.16.
`.github/workflows/build-images-release.yaml` is based on tags and thus should work without modifications. I'm also inclined to change the default branch to `main` instead of the current `master` for consistency with other cilium repository (see https://github.com/cilium/cilium/issues/23110).
=> prepare for branching v0.1

Dockerfile, go.mod
Backport of #249 to the v0.1 branch.
=> v0.1: Bump Golang to v1.22.5

Dockerfile, internal/defaults/defaults.go
See https://github.com/cilium/cilium/pull/34934, needs to be done in certgen v0.1 to be introduced in Cilium v1.15 and v1.14.
=> hubble: client auth for hubble server cert

Dockerfile
Commit e63e7e9f0f0ae1340271b1b3975d5e84187b623b updated the k8s deps to 0.33.0 which require Go v1.24.
=> [v0.1]: bump Go to v1.24.3
